# Integrantes:
* Jennyfer Belalcazar Manrique
* Diego Ledesma Motta
* David barona

In [1]:
import numpy as np

In [58]:
class pointsGenerator:
    def __init__(self):
        pass
    
    def line(self, x1, y1, x2, y2, method):
        if method == 'bresenham':
            #Conditions:
            # * x1 < x2 and y1 < y2
            # * 0 < m < 1
            if (x1 > x2) or (y1 > y2) or ( (y2-y1)/(x2-x1) > 1) or ( (y2-y1)/(x2-x1) < 0):
                print("first if statement")
                raise ValueError('Invalid points for Bresenham algorithm')
            m = 2 * (y2-y1)     
            mErr = m - (x2-x1)  

            y = y1
            points = np.zeros((0,), dtype = np.int32)

            for x in range(x1, x2 + 1): 
                points = np.append(points, np.array([x, y], dtype = np.int32))
                mErr = mErr + m     
                if mErr >= 0:
                    y += 1          
                    mErr = mErr - 2 * (x2 - x1) 

            return points.reshape(-1, 2)

    

    def circle(self, x0, y0, r, method):
        if method == 'mid-point':
            x = r
            y = 0

            points = np.zeros((0,), dtype = np.int32)
            points = np.append(points, np.array([x0 + x, y0 + y], dtype = np.int32))

            if (r > 0):
                points = np.append(points, np.array([x0 + x, y0 - y], dtype = np.int32))
                points = np.append(points, np.array([x0 + y, y0 + x], dtype = np.int32))
                points = np.append(points, np.array([x0 - y, y0 + x], dtype = np.int32))

            p = 1 - r

            while (x > y):
                y += 1

                # Mid-point inside or on the perimeter
                if p <= 0:
                    p = p + 2 * y + 1

                # Mid-point outside the perimeter
                else:
                    x -= 1
                    p = p + 2 * y - 2 * x + 1

                # All the perimeter points have already been printed
                if (x < y):
                    break

                # adding the generated point and its reflections
                points = np.append(points, np.array([x0 + x, y0 + y], dtype = np.int32))
                points = np.append(points, np.array([x0 - x, y0 + y], dtype = np.int32))
                points = np.append(points, np.array([x0 + x, y0 - y], dtype = np.int32))
                points = np.append(points, np.array([x0 - x, y0 - y], dtype = np.int32))

                # If the generated point is on the line x = y then 
                # the perimeter points have already been added
                if (x != y):
                    points = np.append(points, np.array([x0 + y, y0 + x], dtype = np.int32))
                    points = np.append(points, np.array([x0 - y, y0 + x], dtype = np.int32))
                    points = np.append(points, np.array([x0 + y, y0 - x], dtype = np.int32))
                    points = np.append(points, np.array([x0 - y, y0 - x], dtype = np.int32))
                
            return points.reshape(-1, 2)


# Tests

## DDA Line Algorithm

In [46]:
arr0 = np.append(np.zeros((1,1), dtype = np.int32 ), np.array([3,2], dtype = np.int32))
arr1 = np.append(arr0, np.array([5,4], dtype = np.int32))
arr1

array([0, 3, 2, 5, 4], dtype=int32)

In [49]:
plotter = pointsGenerator()
plotter.line(0,0,3,2, 'bresenham')

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]], dtype=int32)

In [50]:
plotter.line(3,2,15,5, 'bresenham')

array([[ 3,  2],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 7,  3],
       [ 8,  4],
       [ 9,  4],
       [10,  4],
       [11,  4],
       [12,  5],
       [13,  5],
       [14,  5],
       [15,  5]], dtype=int32)

## mid-point circle drawing algorithm

In [59]:
circle = pointsGenerator()
circle.circle(0,0,3, 'mid-point')

array([[ 3,  0],
       [ 3,  0],
       [ 0,  3],
       [ 0,  3],
       [ 3,  1],
       [-3,  1],
       [ 3, -1],
       [-3, -1],
       [ 1,  3],
       [-1,  3],
       [ 1, -3],
       [-1, -3],
       [ 2,  2],
       [-2,  2],
       [ 2, -2],
       [-2, -2]], dtype=int32)