# Integrantes:
* Jennyfer Belalcazar Manrique
* Diego Ledesma Motta
* David barona

# DDA Line Algorithm

In [1]:
import numpy as np

In [11]:
class pointsGenerator:
    def __init__(self):
        pass
    
    def line(self, x1, y1, x2, y2, method):
        if method == 'bresenham':
            #Conditions:
            # * x1 < x2 and y1 < y2
            # * 0 < m < 1
            if (x1 > x2) or (y1 > y2) or ( (y2-y1)/(x2-x1) > 1) or ( (y2-y1)/(x2-x1) < 0):
                raise ValueError('Invalid points for Bresenham algorithm')
            m = 2 * (y2-y1)     #4
            mErr = m - (x2-x1)  #1

            y = y1
            points = np.zeros((0,), dtype = np.int32)

            for x in range(x1, x2 + 1): 
                points = np.append(points, np.array([x, y], dtype = np.int32))
                mErr = mErr + m     #1
                if mErr >= 0:
                    y += 1          #3
                    mErr = mErr - 2 * (x2 - x1) #-5

            return points.reshape(-1, 2)

In [8]:
np.append(np.zeros((0,), dtype = np.int32 ), np.array([3,2], dtype = np.int32))

array([3, 2], dtype=int32)

In [12]:
plotter = pointsGenerator()
plotter.line(0,0,3,2, 'bresenham')

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]], dtype=int32)

In [13]:
plotter.line(3,2,15,5, 'bresenham')

array([[ 3,  2],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 7,  3],
       [ 8,  4],
       [ 9,  4],
       [10,  4],
       [11,  4],
       [12,  5],
       [13,  5],
       [14,  5],
       [15,  5]], dtype=int32)