# Integrantes:
* Jennyfer Belalcazar Manrique
* Diego Ledesma Motta
* David barona

In [1]:
import numpy as np

# Class definition

In [27]:
class pointsGenerator:
    def __init__(self):
        pass
    
    def line(self, x1, y1, x2, y2, method):
        if method == 'bresenham':
            #Conditions:
            # * x1 < x2 and y1 < y2
            # * 0 < m < 1
            if (x1 > x2) or (y1 > y2) or ( (y2-y1)/(x2-x1) > 1) or ( (y2-y1)/(x2-x1) < 0):
                print("first if statement")
                raise ValueError('Invalid points for Bresenham algorithm')
            m = 2 * (y2-y1)     
            mErr = m - (x2-x1)  

            y = y1
            points = np.zeros((0,), dtype = np.int32)

            for x in range(x1, x2 + 1): 
                points = np.append(points, np.array([x, y], dtype = np.int32))
                mErr = mErr + m     
                if mErr >= 0:
                    y += 1          
                    mErr = mErr - 2 * (x2 - x1) 

            return points.reshape(-1, 2)

    

    def circle(self, x0, y0, r, method):
        if method == 'mid-point':
            x = r
            y = 0

            points = np.zeros((0,), dtype = np.int32)
            points = np.append(points, np.array([x0 + x, y0 + y], dtype = np.int32))
            print("first point:", points)

            if (r > 0):
                points = np.append(points, np.array([x0 + x, y0 - y], dtype = np.int32))
                points = np.append(points, np.array([x0 + y, y0 + x], dtype = np.int32))
                points = np.append(points, np.array([x0 - y, y0 + x], dtype = np.int32))

            p = 1 - r
            print("p = ", 1, " - ", r)
            print("p = ", p)

            iteration = 0

            while (x > y):
                iteration += 1 #debugging
                print("iteration:", iteration) 
                y += 1

                

                # Mid-point inside or on the perimeter
                if p <= 0:
                    print("p <= 0")
                    print("p = ",p, " + ", 2 * y, " + ", 1)
                    p = p + 2 * y + 1
                    print("p = ", p)
                    

                # Mid-point outside the perimeter
                else:
                    x -= 1
                    print("p = ",p, " + ", 2 * y, " - ", 2 * x, " + ", 1)
                    p = p + 2 * y - 2 * x + 1
                    print("p = ", p)

                #print("p = ", p)

                # All the perimeter points have already been printed
                if (x < y):
                    break

                # adding the generated point and its reflections
                points = np.append(points, np.array([x0 + x, y0 + y], dtype = np.int32))
                print("next point: ", points[-2:])
                points = np.append(points, np.array([x0 - x, y0 + y], dtype = np.int32))
                points = np.append(points, np.array([x0 + x, y0 - y], dtype = np.int32))
                points = np.append(points, np.array([x0 - x, y0 - y], dtype = np.int32))

                # If the generated point is on the line x = y then 
                # the perimeter points have already been added
                if (x != y):
                    points = np.append(points, np.array([x0 + y, y0 + x], dtype = np.int32))
                    #print("next point: ", points[-2:])
                    points = np.append(points, np.array([x0 - y, y0 + x], dtype = np.int32))
                    points = np.append(points, np.array([x0 + y, y0 - x], dtype = np.int32))
                    points = np.append(points, np.array([x0 - y, y0 - x], dtype = np.int32))
                
            return points.reshape(-1, 2)


# Tests

## Bresenham's Line Algorithm

In [3]:
arr0 = np.append(np.zeros((1,1), dtype = np.int32 ), np.array([3,2], dtype = np.int32))
arr1 = np.append(arr0, np.array([5,4], dtype = np.int32))
arr1

array([0, 3, 2, 5, 4], dtype=int32)

In [4]:
plotter = pointsGenerator()
plotter.line(0,0,3,2, 'bresenham')

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]], dtype=int32)

In [5]:
plotter.line(3,2,15,5, 'bresenham')

array([[ 3,  2],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 7,  3],
       [ 8,  4],
       [ 9,  4],
       [10,  4],
       [11,  4],
       [12,  5],
       [13,  5],
       [14,  5],
       [15,  5]], dtype=int32)

## mid-point circle drawing algorithm

In [28]:
circle = pointsGenerator()
circle.circle(0,0,3, 'mid-point')

first point: [3 0]
p =  1  -  3
p =  -2
iteration: 1
p <= 0
p =  -2  +  2  +  1
p =  1
next point:  [3 1]
iteration: 2
p =  1  +  4  -  4  +  1
p =  2
next point:  [2 2]


array([[ 3,  0],
       [ 3,  0],
       [ 0,  3],
       [ 0,  3],
       [ 3,  1],
       [-3,  1],
       [ 3, -1],
       [-3, -1],
       [ 1,  3],
       [-1,  3],
       [ 1, -3],
       [-1, -3],
       [ 2,  2],
       [-2,  2],
       [ 2, -2],
       [-2, -2]], dtype=int32)

In [29]:
circle.circle(3,5,5, 'mid-point')

first point: [8 5]
p =  1  -  5
p =  -4
iteration: 1
p <= 0
p =  -4  +  2  +  1
p =  -1
next point:  [8 6]
iteration: 2
p <= 0
p =  -1  +  4  +  1
p =  4
next point:  [8 7]
iteration: 3
p =  4  +  6  -  8  +  1
p =  3
next point:  [7 8]
iteration: 4
p =  3  +  8  -  6  +  1
p =  6


array([[ 8,  5],
       [ 8,  5],
       [ 3, 10],
       [ 3, 10],
       [ 8,  6],
       [-2,  6],
       [ 8,  4],
       [-2,  4],
       [ 4, 10],
       [ 2, 10],
       [ 4,  0],
       [ 2,  0],
       [ 8,  7],
       [-2,  7],
       [ 8,  3],
       [-2,  3],
       [ 5, 10],
       [ 1, 10],
       [ 5,  0],
       [ 1,  0],
       [ 7,  8],
       [-1,  8],
       [ 7,  2],
       [-1,  2],
       [ 6,  9],
       [ 0,  9],
       [ 6,  1],
       [ 0,  1]], dtype=int32)